#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    filemanager = "nerdtree"
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    default_indent = 4

    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    # Enable/Disable show mode on statusline
    enable_statusline_mode = true

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'input method',
       'fileformat',
    ]

    project_rooter_patterns = ['Cargo.toml', '.SpaceVim.d/', '.git/', '.clang']
    project_rooter_outermost = false

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'core'
filetree_show_hidden = true

[[layers]]
name = "sudo"

[[layers]]
name = "leaderf"

[[layers]]
name = "lsp"
filetypes = [
    "rust",
    "c",
    "cpp",
]
enabled_clients = ['vimls', 'clangd', 'rust_analyzer']
    [layers.override_cmd]
        rust = ["rust-analyzer"]

[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true
format_on_save = true

[[layers]]
name = 'lang#rust'
format_on_save = true
racer_cmd = "rust-analyzer"

[[layers]]
name = "lang#extra"

[[layers]]
name = "lang#toml"

[[layers]]
  name = "autocomplete"

