[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.primary]
background = "#131313"
foreground = "#DDDDDD"

[colors.normal]
black = "#DDDDDD"
red = "#c74028"
green = "#62BA46"
yellow = "#ded9b7"
blue = "#c28b12"
magenta = "#c72855"
cyan = "#fdd888"
white = "#131313"

[colors.bright]
black = "#57564F"
red = "#e7988a"
green = "#b0dca2"
yellow = "#f0edde"
blue = "#f1c464"
magenta = "#efb0c2"
cyan = "#fef1d5"
white = "#303030"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 10.0
normal = { family = "Fira Code", style = "Retina" }
bold = { family = "Fira Code", style = "Bold" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = false
bindings = [{ action = "PasteSelection", mouse = "Middle" }]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
class = "Alacritty"
decorations = "None"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
dimensions = { columns = 95, lines = 75 }
opacity = 1
padding = { x = 10, y = 10 }

[general]
live_config_reload = true
working_directory = "None"
import = [
  "~/.config/alacritty/keybindings.toml",
]
