
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xd54e53"
white = "0xeaeaea"
yellow = "0xe6c547"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 10.0
normal = { family = "Fira Code", style = "Retina" }
bold = { family = "Fira Code", style = "Bold" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = false
bindings = [
  { action = "PasteSelection", mouse = "Middle" }
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
class = "Alacritty"
decorations = "full"
dynamic_padding = false
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
dimensions = { columns = 95, lines = 75 }

[general]
live_config_reload = true
working_directory = "None"
import = [
  "~/.config/alacritty/keybindings.toml",
]

